name: deploy

on:
  workflow_run:
    workflows: ["check"]
    branches: [main]
    types:
      - completed
  # schedule:
    # - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    outputs:
      build_id: ${{ steps.passing.outputs.build_id }}
    steps:
      - name: Wait for check workflows_run to succeed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - name: Go On
        if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
          ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
          git checkout $ref
        shell: bash
      - name: Checkout
        uses: ./.github/checkout
      - name: Prearing
        id: prearing

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Building
        id: passing
        if: ${{ success() && steps.prearing.conclusion == 'success' }}
        run: |
          sleep 40
          echo "::set-output name=build_id::$BUILD_ID"
  
  deploy: 
    if:  ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: clone repo
        run: |
            git config --global --add safe.directory $(pwd)
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
            ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
            git checkout $ref
        shell: bash
      
      - name: checkout
        id: checkout
        uses: ./.github/checkout

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: build
        run: echo ğŸ‘‹ğŸ‘ğŸ‘ğŸ‘ SUCCESS ğŸ‘‹ğŸ‘ğŸ‘ğŸ‘! ${{ needs.build.outputs.build_id }}
      
      - name: deploy
        if:  ${{ success() }}

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
